#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var docopt, sm, glob, path, doc, getOption, o, prefix, dir, files, opts, sitemap;
  docopt = require('docopt').docopt;
  sm = require('sitemap');
  glob = require('glob');
  path = require('path');
  doc = "Usage:\n    sitemap-cli generate DIR -p PREFIX \n    sitemap-cli -h | --help \n\nOptions:\n    -p, --prefix PREFIX     Url prefix to be used\n\nArguments:\n    DIR                     Root of the website";
  getOption = function(a, b, def, o){
    if (!o[a] && !o[b]) {
      return def;
    } else {
      return o[b];
    }
  };
  o = docopt(doc);
  prefix = getOption('-p', '--prefix', '', o);
  dir = o['DIR'];
  if (prefix !== '') {
    files = glob.sync("**/*.html", {
      cwd: dir + "/"
    });
    files = files.map(function(it){
      return {
        url: "/" + it,
        changefreq: 'daily',
        priority: 0.5
      };
    });
    opts = {
      hostname: prefix,
      cacheTime: 600000,
      urls: files
    };
    sitemap = sm.createSitemap(opts);
    sitemap.toXML(function(xml){
      return console.log(xml);
    });
  }
}).call(this);
